### ISSUE TITLE
Question: which parts of this repository are broken for latest three.js build

### ISSUE THREAD

**Issue by Wilt** [collinhover/threeoctree#11]
In the docs is written:

> This build is stable up to THREE.js ~r60

I would like to know which parts of this repository are not working with the latest build of `three.js`. Can I not use `threeoctree` at all in r78? Or are only some of the features broken?

I don't mind contributing with some PR's to help get the repository up to date (when I have some time to kill) with latest three.js but then it would be good to know in advance which parts need attention.

**Comment by collinhover** [comment]
Hi Wilt! I wrote that into the docs to warn other devs of which version of THREE I maintained the octree until. I don't know if it works with the current version or what may be broken, because I haven't used THREE in a long time. Sorry!

**Comment by Wilt** [comment]
@collinhover No worries. I can check out if all is working and give some feedback here.
