### ISSUE TITLE
octree raycasting returns unordered intersects array

### ISSUE THREAD

**Issue by Wilt** [collinhover/threeoctree#13]
This issue can also be noticed in this example:

http://threejs.org/examples/webgl_octree_raycasting.html

When hovering with the mouse on (some of the) boxes in front of the statue the statue is highlighted. This is caused by the fact that the intersects array that is returned by the `intersectOctreeObjects` method is not ordering the results. This behavior is different from normal raycasting where the objects are ordered (closest object is first in the array).

Is this intentional?
Or can the code be updated to return objects in an ordered array?

**Comment by collinhover** [comment]
I don't remember why I setup `intersectOctreeObjects` to return an unsorted array, but my best guess is that my use cases did not need sorted results and so I didn't want to include the overhead of sorting. Are you not able to sort the results of `intersectOctreeObjects` yourself?

**Comment by Wilt** [comment]
Yes, that's not the problem...
Would an optional `sort` flag (true/false) be an option?

**Comment by collinhover** [comment]
Sure, it'd have to be the third parameter to the method and not get passed recursively (so the sorting would only happen at the end of the top level call). I don't have time to implement and test this, but I'll review and merge a PR if you want to propose a change :)

**Comment by Wilt** [comment]
PR here: https://github.com/collinhover/threeoctree/pull/15
