### ISSUE TITLE
Use distanceSquared in findClosestVertex

### ISSUE THREAD

**Issue by kpetrow** [collinhover/threeoctree#23]
Was wondering if this would be a valid PR?

line 590:
`distance = vertices[i].distanceTo(localPosition);`
change to:
`distance = vertices[i].distanceToSquared(localPosition);`

**Comment by collinhover** [comment]
What are you trying to fix? Is this just for performance reasons?

**Comment by kpetrow** [comment]
Yes, No reason to calculate the distance till the end.  You could do a single SQRT.

**Comment by collinhover** [comment]
Definitely! However, I'd recommend you look at the latest version hosted on the THREEJS repo and see if they haven't already fixed this. If not, submit a PR there :)
